# -*- coding: utf-8 -*-
"""Day 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UcdZcMzZdfAk3eIsO1Ix6y6xfqvOSGms
"""

import numpy as np
import keras

model = keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])
model.compile(optimizer='sgd', loss='mean_squared_error')

x = np.array([1.0, 2.0, 3.0, 4.0, 5.0], dtype=float)
y = np.array([2.0, 4.0, 6.0, 8.0, 10.0], dtype=float)

model.fit(x,y, epochs=500)
print(model.predict([10.0]))