# -*- coding: utf-8 -*-
"""mini project .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vQpr0nH3PIYmvu3ylYst4oHtM0Ncyw3_
"""

import tensorflow as tf
import seaborn as sns
import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload()

brain_stroke = pd.read_csv('brain_stroke.csv')
print(brain_stroke)

brain_stroke.columns

brain_stroke['gender'] = brain_stroke['gender'].map({'Male':1, 'Female':0})
brain_stroke.head()

brain_stroke['ever_married'] = brain_stroke['ever_married'].map({'Yes':1, 'No': 0})
brain_stroke.head()

brain_stroke['work_type'] = brain_stroke['work_type'].map({'Private':0, 'Self-employed':1, 'Govt_job':2, 'children':3})
brain_stroke.head()

brain_stroke['Residence_type'] = brain_stroke['Residence_type'].map({'Urban':1, 'Rural':0})
brain_stroke.head()

brain_stroke['smoking_status'] = brain_stroke['smoking_status'].map({'formerly smoked':0, 'never smoked':1, 'smokes':2, 'Unknown':3})
brain_stroke.head()

sns.barplot('hypertension', 'stroke', data=brain_stroke)

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

x = brain_stroke.drop('stroke', axis=1)
y = brain_stroke['stroke']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

cla = RandomForestClassifier()
cla.fit(x_train, y_train)
pre = cla.predict(x_test)
accuracy_score(y_test, pre)