# -*- coding: utf-8 -*-
"""day5/6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1poTjuhqpYgDfW09svNAtuRngcpn7VunU

first program
"""

import pandas as pd
import numpy as np

arr1 = np.array([[9.0,8.0,7.0,5.0,9.0],[6.0,5.0,4.0,7.8,6.9],[9.0,4.0,4.1,7.8,4.9]])
print(arr1)

arr2 = np.array([[9.0,8.0,7.0,5.0,9.0,4.0,3.2,7.9],[6.0,5.0,4.0]],
                dtype =object)  
print(arr2)

"""second program"""

import pandas as pd
import numpy as np

# Get Dimension
print('Dimension of Array 1-',arr1.ndim)
print('Dimension of Array 2-',arr2.ndim)

# Get Shape
print('Shape of Array 1-',arr1.shape)
print('Shape of Array 2-',arr2.shape)

# Get Type
print('Type of Array 1-',arr1.dtype)  #refering above array1
print('Type of Array 2-',arr2.dtype)  #refering above array2
# Get Size
print('Size ',arr1.itemsize)

# Get number of elements
print('number of elements ',arr1.size)

"""third program  Acessing and Manipulating Arrays"""

# Get a specific element [r, c]
print(arr1[0, 4])

# Get a specific row 
print(arr1[0, :])

# Get a specific column
print(arr1[:, 2])

# Get a specific column
print(arr2[:, 2])

# Getting a little more fancy [startindex:endindex:stepsize]
print(arr1[1, 2:-1:4])

"""as per day 5/6 mini project of data cleaning from tata steel

```
# This is formatted as code
```


"""

from google.colab import files


uploaded = files.upload()

import numpy as np
import pandas as pd
import seaborn as sns
import os

print(os.listdir())

df = pd.read_csv("tatasheel.csv")
df

df.isnull().sum()  #identify the null values from csv

sns.heatmap(df.isnull(), yticklabels=False)