# -*- coding: utf-8 -*-
"""1stday.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DuGbJxpCVKjiRFYv_xS5LBa20RsR4joA
"""

import matplotlib.pyplot as plt
import numpy as np
import statsmodels.api as sm
import pylab as py

# HISTOGRAM
x = np.random.normal(200, 30, 150)

# print(x)
plt.hist(x)
plt.show()

# PIE CHART
y = np.array([45, 15, 35, 25, 45, 12, 30])
# print(y)
plt.pie(y)
plt.show()

# SCATTER PLOT
x = np.random.normal(10, 20, 350)
y = np.random.normal(10, 20, 350)

plt.scatter(x, y)
plt.show()

# BAR PLOT
x = np.array(["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"])
y = np.random.normal(20, 10, 10)

plt.bar(x,y)
plt.show()

# LINE GRAPH
x = np.array([35, 25, 25, 15, 34, 45, 56, 67, 89, 11, 22, 33, 44, 55, 66])  # X-axis points
y = np.array([12, 22, 444, 563, 990, 90, 56, 67, 89, 11, 22, 33, 44, 55, 66])  # Y-axis points
  
plt.plot(x, y)  # Plot the chart
plt.show()