# -*- coding: utf-8 -*-
"""pandas_numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YQQ4BF-9FuQZjW-gJcRagFsv7Zs9OqIp
"""

import pandas as pd
import numpy as np


## 1. Creating a DataFrame.
data = {'name': ['Jay', 'Ron', 'joe', 'Ross'],
        'age': ['5', '10', '7', '6'],
        'score': [9.4, 8.9, 7.2, 9]} 
        
df=pd.DataFrame(data)

rows, columns = df.shape
print('rows',rows)
print('columns',columns)

## Head prints first n number of rows
print(df.head(5))

## Head prints first n number of columns
print(df.tail(3))

## Slicing a Dataframe
print(df.iloc[0])
print(df.iloc[0,0:3])

## Descibe
df.describe()