# -*- coding: utf-8 -*-
"""practical 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CX8_rdpfLXwuKlCt7sO3XJGZ9g0NTpCt
"""

#pandas program
#example of series

import pandas as pd 
a = [1,7,2]
myvar = pd.Series(a, index = ["x", "y", "z"])
print(myvar)

#exam of dataframe

import pandas as pd

data = {
  "calories": [420, 380 ,390, 500],
  "duration": [50, 40 ,45,30]
}

#load data into a dataframe object:
df = pd.DataFrame(data)

print(df)

#exam of dataframe

import pandas as pd

data = {
  "students": ["Kaustubh", "sapna" ,"sheetal", "yash"],
  "roll No.": [51, 40 ,45,30],
  "address": ["chembur", "kalyan", "dadar", "sion"],
  "email Id": ["kaustubh@gmail.com", "sapna@gmail.com", "sheetal@gmail,.com", "yash@gmail.com"]
}

#load data into a dataframe object:
df = pd.DataFrame(data)

print(df)

import pandas as pd
from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("data1 (1).csv")
print(df)