# -*- coding: utf-8 -*-
"""day 8_seaborn_matlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UqkLk8S_wOm9mqAPCPLkPsRf3EyOjIRU

Day 8th work on seaborn and matplotlib programs
"""

import seaborn as sns
from matplotlib import pyplot as plt
import os
import numpy as np
import pandas as pd

from google.colab import files


uploaded = files.upload()

print(os.listdir())

df = pd.read_csv("tatasheel.csv")

fmri=sns.load_dataset("fmri")
fmri.head()

sns.lineplot(x="timepoint",y="signal",data=fmri)
plt.show()

sns.lineplot(x="timepoint",y="signal",hue="event",data=fmri,style="event",markers=True)
plt.title("Plot Smooth Curve")
plt.show()



